SET SCHEMA 'zafira';

DO $$

    DECLARE INTEGRATION_TYPE_ID INTEGRATION_TYPES.ID%TYPE;
    DECLARE INTEGRATION_ID INTEGRATIONS.ID%TYPE;
    DECLARE INTEGRATION_PARAM_ID INTEGRATION_PARAMS.ID%TYPE;

    BEGIN
        -- Jenkins
        INSERT INTO INTEGRATION_PARAMS(NAME, METADATA, MANDATORY, INTEGRATION_TYPE_ID, NEED_ENCRYPTION) VALUES ('JENKINS_JOB_URL_VISIBILITY', '{"paramType": "BOOLEAN"}', FALSE, INTEGRATION_TYPE_ID, FALSE) RETURNING ID INTO INTEGRATION_PARAM_ID;
        INSERT INTO INTEGRATION_SETTINGS(VALUE, INTEGRATION_ID, INTEGRATION_PARAM_ID, VALUE) VALUES ('false', INTEGRATION_ID, INTEGRATION_PARAM_ID, TRUE);

END$$;
